// Copyright (c) HashiCorp, Inc
// SPDX-License-Identifier: MPL-2.0
import * as fs from "fs-extra";
import * as path from "path";
import {
  Language,
  TerraformDependencyConstraint,
  TerraformTargetVersions,
} from "@cdktn/commons";
import { createTmpHelper } from "./util";

const mockReadSchema = jest.fn();
jest.mock("@cdktn/provider-schema", () => ({
  readSchema: (...args: unknown[]) => mockReadSchema(...args),
}));

// Imported after the mock so ConstructsMaker picks up the mocked readSchema.
import { ConstructsMaker, GetOptions } from "../constructs-maker";

const tmp = createTmpHelper();

const constraint: TerraformDependencyConstraint = {
  fqn: "hashicorp/random",
  name: "random",
  source: "hashicorp/random",
  version: "3.1.3",
};

// Minimal schema - no resources/data sources - so generation stays within
// pure TypeScript emission (no jsii-pacmak invocation), mirroring the
// "empty-provider-resources" fixture used elsewhere in this package.
const fakeSchema = {
  providerSchema: {
    format_version: "0.2" as const,
    provider_schemas: {
      "registry.terraform.io/hashicorp/random": {
        resource_schemas: null,
        data_source_schemas: null,
      },
    },
    provider_versions: {
      "registry.terraform.io/hashicorp/random": "3.1.3",
    },
    cli_name: "terraform",
    cli_version: "1.7.5",
  },
};

describe("targetVersions threading through 'cdktn get'", () => {
  beforeEach(() => {
    mockReadSchema.mockReset();
    mockReadSchema.mockResolvedValue(fakeSchema);
  });

  it("passes GetOptions.targetVersions through to readSchema", async () => {
    const workdir = tmp("target-versions-thread.test");
    const targetVersions: TerraformTargetVersions = { terraform: ">=1.5.7" };
    const options: GetOptions = {
      codeMakerOutput: workdir,
      targetLanguage: Language.TYPESCRIPT,
      targetVersions,
    };

    const maker = new ConstructsMaker(options, "/some/cache/path");
    await maker.generate([constraint]);

    expect(mockReadSchema).toHaveBeenCalledWith(
      [constraint],
      "/some/cache/path",
      targetVersions,
    );
  });

  it("omits targetVersions from the readSchema call when not configured", async () => {
    const workdir = tmp("target-versions-absent.test");
    const options: GetOptions = {
      codeMakerOutput: workdir,
      targetLanguage: Language.TYPESCRIPT,
    };

    const maker = new ConstructsMaker(options);
    await maker.generate([constraint]);

    expect(mockReadSchema).toHaveBeenCalledWith(
      [constraint],
      undefined,
      undefined,
    );
  });

  it("stamps constraints.json with targetVersions + cli identity, and older constraints.json files without those fields are still treated as fresh (no forced regeneration)", async () => {
    const workdir = tmp("target-versions-stamp.test");
    const targetVersions: TerraformTargetVersions = { terraform: ">=1.5.7" };
    const options: GetOptions = {
      codeMakerOutput: workdir,
      targetLanguage: Language.TYPESCRIPT,
      targetVersions,
    };

    const maker = new ConstructsMaker(options);
    await maker.generate([constraint]);

    const constraintsFile = JSON.parse(
      await fs.readFile(path.join(workdir, "constraints.json"), "utf8"),
    );
    expect(constraintsFile.targetVersions).toEqual(targetVersions);
    expect(constraintsFile.cli).toEqual({
      name: "terraform",
      version: "1.7.5",
    });

    // Rewrite constraints.json as it would have looked before this feature
    // landed (no targetVersions/cli fields), keeping the rest identical -
    // this simulates re-running `cdktn get` against an output directory
    // generated by an older cdktn version.
    const {
      targetVersions: _tv,
      cli: _cli,
      ...legacyConstraints
    } = constraintsFile;
    await fs.writeFile(
      path.join(workdir, "constraints.json"),
      JSON.stringify(legacyConstraints, null, 2),
    );

    const maker2 = new ConstructsMaker(options);
    const toGenerate = await maker2.filterAlreadyGenerated([constraint]);
    expect(toGenerate).toEqual([]);
  });
});
